baseurl = "/"
languageCode = "en-us"
title = "atmos.org"
theme = "hugo-strata-theme"
disqusShortname = "spf13"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Corey Donohoe"
	description = "Kind of human-like"

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []


	[params.sidebar]
    background = "bg.jpg"
		# Replace the avatar with a picture of your own under static/images
		avatar = "avatar.jpg"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "**I'm Corey Donohoe** I live in NYC."
		# The icons will be shown if you enter your username
		twitter = "atmos"
		github = "atmos"
		dribbble = ""
		facebook = "corey.donohoe"
		googleplus = ""
		flickr = "atmos"
		linkedin = ""

		copyright = [
			"&copy; atmos.org"
		]


	[params.about]
		hide  = false
		title = "This is atmos.org..."
		content = "It's mainly an archive of various open source projects. If we're old friends, get in touch via the links below."


	[params.portfolio]
		hide  = false
		title = ""

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
			image = "dogs/fulls/bailey1.jpg"
			thumb = "dogs/thumbs/bailey1.png"
			title = ""

		[[params.portfolio.gallery]]
			image = "dogs/fulls/alia2.jpg"
			thumb = "dogs/thumbs/alia2.png"
			title = ""

		[[params.portfolio.gallery]]
			image = "dogs/fulls/zerodog.jpg"
			thumb = "dogs/thumbs/zerodog.png"
			title = ""

		[[params.portfolio.gallery]]
			image = "dogs/fulls/99-0.jpg"
			thumb = "dogs/thumbs/99-0.png"
			title = ""

	[params.recentposts]
		hide  = true
		title = "Recent blog posts"

	[params.contact]
		hide  = true
		title = "Get In Touch"
		content = "Accumsan pellentesque commodo blandit enim arcu non at amet id arcu magna. Accumsan orci faucibus id eu lorem semper nunc nisi lorem vulputate lorem neque lorem ipsum dolor."

		address = [
			"1234 Somewhere Rd.",
			"Nashville, TN 00000",
			"United States"
		]
		phone = "000-000-0000"

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = ""

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Name"
			email = "Email"
			message = "Message"
			submit = "Send message"


# Menu links that appear on the left sidebar
[[menu.main]]
	name = "Home"
	url  = "/"
	weight = 0
       hide = true

#[[menu.main]]
#	name = "Quips"
#	url  = "post/"
#	weight = 10
